### ISSUE TITLE
How about contain `dist` folder when publishing

### ISSUE THREAD

**Issue by sohee-lee7** [markushedvall/plantuml-encoder#10]
I want to use already built `plantuml-encoder`. So I suggest that `plantuml-encoder` will publish with `dist` folder by removing below option of `package.json`.

``` json
  "standard": {
    "ignore": "dist/"
  }
```

**Comment by markushedvall** [comment]
So I assume this is for none NodeJS environment?

Do you have any examples of other packages that do this? I would like to know how it's usually organised.

**Comment by markushedvall** [comment]
Actually the lines you wrote is for ignoring dist/ for linting. It is .npmignore that needs to be modified.

But instead whitelisting should be used instead of blacklisting. Removing .npmignore and adding dist/ to the list of files in packages.json

One example of another project that does this is https://github.com/nodeca/pako, which is what I think I used as inspiration originally.

**Comment by markushedvall** [comment]
Fixed in 143e4b657a060333408ea852d8e104bcbff74981 and included in 1.2.6 release.
Please inform me if you are still having issues.
